### ISSUE TITLE
Adding the Deparse function

### ISSUE THREAD

**Issue by stephenafamo** [wasilibs/go-pgquery#20]
First of all, great work on this package.

I would like to use this to replace my use of `pg_query_go` in Bob, but the absence of the `Deparse` function is holding me back.

To explain the use case:  
In my tests for Bob, I compare the SQL queries generated by the query builder with an expected SQL text.  
Of course, I first parse both queries to catch any errors, but then I `Deparse` the queries from the parse tree to sort of "normalize" them. This will remove the need to exactly match things like extra parenthesis, cases of keywords, e.t.c.

How possible is it to add this function?

**Comment by anuraaga** [comment]
Thanks for the report @stephenafamo! This was just accidentally missed, possibly because pg_query_go doesn't have a unit test for it. I've implemented it in #21.

**Comment by anuraaga** [comment]
BTW, one thing to keep in mind is that performance has not been a priority for this package since the first use case was sqlc, an offline dev tool. There are some techniques to improve it, probably dramatically from where we're at now, though they're a bit complicated - I can look into trying them though maybe not so soon. IIUC, Bob is meant for the hot path within actual API servers for example, so you'll want to benchmark to see how things go for you - perhaps its fine if users are able to opt-in to the cgo backend with `pgquery_cgo` build tag. Cheers.

**Comment by stephenafamo** [comment]
The hot path for Bob does not go through this parser. It is used only for tests, so I don't mind the performance at all
